org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=1.21.1
minecraft_version_range=[1.21,1.22)
neo_version=21.1.206
neo_version_range=[21.0.0-beta,)
loader_version_range=[4,)

parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17

mod_id=galosphere
mod_name=Galosphere
mod_license=All-Rights-Reserved
mod_version=1.4.5
mod_group_id=net.orcinus.galosphere
mod_authors=Orcinus
mod_description=Galosphere aims to improve the underground by adding new biomes and feature
