modLoader="javafml"
loaderVersion="[39,)"
license="All rights reserved"
[[mods]]
modId="galosphere"
version="1.20.1-1.4.1"
displayName="Galosphere"
logoFile= "galosphere.png"
authors="Orcinus"
description='''
Galosphere is a mod that aims to overhaul the underground

Author:
- Orcinus

Contributors:
- Ninni
- bunten

'''
[[dependencies.galosphere]]
    modId="forge"
    mandatory=true
    versionRange="[39,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.galosphere]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20,1.21)"
    ordering="NONE"
    side="BOTH"
