modLoader="javafml"
loaderVersion="[39,)"
license="All rights reserved"
[[mods]]
modId="galosphere"
version="1.20.1-1.4.0"
displayName="Galosphere"
logoFile= "galosphere.png"
authors="Orcinus"
description='''
This mod enhances the underground by adding new content to the base game

Author:
- Orcinus

Artist:
- Ninni

Sound Desinger:
- Bunten

'''
[[dependencies.galosphere]]
    modId="forge"
    mandatory=true
    versionRange="[39,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.galosphere]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20,1.21)"
    ordering="NONE"
    side="BOTH"
